### ISSUE TITLE
"Source comment" is lost when converting from xlsx to po

### ISSUE THREAD

**Issue by JensMertelmeyer** [wichert/po-xls#12]
When using `xls-to-po`, the exported .po file does not contain the source code comments whereas `po-to-xls` perfectly transfers the source code comments from PO to Excel.

I have no experience with Python, but from what I can make out from the source code, it looks to me as if `ColumnHeaders.comment` was simply forgot here? I would like to submit a PR but I don't even know Python, so this is a lost cause.

https://github.com/wichert/po-xls/blob/24b7c5c2e05164acd8d752f537ed8e8d72d2ed79/src/poxls/xls_to_po.py#L64-L66

Many thanks for your time.

**Comment by wichert** [comment]
This should be fixed by #13. Thanks!
