### ISSUE TITLE
Provide binaries or building instructions

### ISSUE THREAD

**Issue by JensMertelmeyer** [wichert/po-xls#18]
I am unable to compile this as I am not a python user. The most frustrating thing is that I remember getting it work on an older Windows computer.

Is it a feasible option to provide pre-built binaries for operating systems like Windows?
Or at least a short walkthrough on how to build this?

**Comment by wichert** [comment]
There are no binaries involved; you install po-xls as a script that is run by the Python interpreter.

If you have Python installed you should be able to just do `pip install po-xls`. You can find full details on [this site](https://packaging.python.org/tutorials/installing-packages/), or perhaps [this page with some Windows examples](https://datatofish.com/install-package-python-using-pip/). Both are top hits from searching for "how to install a python package".
