### ISSUE TITLE
Duplicate messageID with different context get lost

### ISSUE THREAD

**Issue by mdezwart** [wichert/po-xls#7]
I noticed that when having a duplicate (msgid), but with different context (msgctxt). The second msgid is not put in the excel sheet

```
msgid ""
msgstr ""
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Language: nl\n"
"X-Source-Language: en\n"
"X-Qt-Contexts: true\n"

msgctxt "Context1"
msgid "test1"
msgstr "Test één"

msgctxt "Context2"
msgid "test1"
msgstr "Test twee"
```

**Comment by wichert** [comment]
I completely missed this ticket for some reason, and discovered the same thing myself today. A new 1.4.1 release with this fixed is available now.
